# This script counts how many seed orthologs in an OG,
# according to EmapperSeedMerge.tsv files generated by 03.EmapperSeedMerge.py,
# and Orthogroups.tsv from OrthoFinder.
# usage: python 04.OrthoGroupSeedAnno.py .EmapperSeedMerge.tsv
# The output file format:
# OrthogroupID - Seed N with most smORFs - smORF number in Seed N - Total smORF number in all seeds -
# - Total smORF number - Raw data for seeds

import sys

ortho_file = "Orthogroups.tsv"
seed_file = sys.argv[1]
# Make sure that the species orders in seed_file and ortho_file columns are consistent!!

output_file = "OrthoStat.og_seed_stat.tsv"

seed_map = {}
spe_list = []
with open(seed_file) as f_in:
	for line in f_in:
		elements = line.strip("\n").split("\t")
		if elements[0] not in seed_map:
			spe_list.append(elements[0])
			seed_map[elements[0]] = {}
		else:
			seed_map[elements[0]][elements[1]] = elements[2]

with open(ortho_file) as f_in, open(output_file,"w") as f_out:
	head_line = f_in.readline()
	for line in f_in:
		total = 0
		anno = 0
		seed_dict = {}
		elements = line.strip("\n").split("\t")
		og_id = elements[0]
		for i in range(1, len(seed_map)+1):
			if elements[i] != "":
				spe = spe_list[i-1]
				gene_list = elements[i].split(",")
				for gene in gene_list:
					gene = gene.lstrip()
					total += 1
					if gene in seed_map[spe]:
						anno += 1
						seed = seed_map[spe][gene]
						if seed in seed_dict:
							seed_dict[seed] += 1
						else:
							seed_dict[seed] = 1
		if anno != 0:
			max_num = 0
			for key,value in seed_dict.items():
				if value > max_num:
					max_num = value
					max_ortho = key
			new_line_list = [og_id, max_ortho, str(max_num), str(anno), str(total)]
			new_line = "\t".join(new_line_list) + "\t" + str(seed_dict) + "\n"
			f_out.write(new_line)





