# usage: python3 BlastResultFilter.py BlastM_N.txt L S
# to filter hits in blast file generated by OrthoFinder, retain hits:
# 1) with alignment lenth, longer than ratio L * (Total length)
# 2) with pident, more than the ratio S
# This script also need SpeciesM.fa.fai and SpeciesN.fa.fai to process

import sys

input_file = sys.argv[1]
output_file = input_file + ".filtered.txt"
l_cutoff = float(sys.argv[2])
s_cutoff = float(sys.argv[3])


species_pair = input_file[5:-4].split("_")
file_m = "Species" + species_pair[0] + ".fa.fai"
dict_m = {}
with open(file_m) as f_in:
	for line in f_in:
		elements = line.strip().split("\t")
		dict_m[elements[0]] = elements[1]
file_n = "Species" + species_pair[1] + ".fa.fai"
dict_n = {}
with open(file_n) as f_in:
	for line in f_in:
		elements = line.strip().split("\t")
		dict_n[elements[0]] = elements[1]

with open(input_file) as f_in, open(output_file,"w") as f_out:
	for line in f_in:
		elements = line.strip().split("\t")
		prot_m = elements[0]
		prot_n = elements[1]
		if prot_m == prot_n:
			continue
		m_len = int(dict_m[prot_m])
		n_len = int(dict_n[prot_n])
		p_ident = float(elements[2])/100
		align_len = int(elements[3])
		align_ratio = min(align_len/m_len, align_len/n_len)
		if align_ratio >= l_cutoff and p_ident >= s_cutoff:
			f_out.write(line)

